### ISSUE TITLE
Problem with Basic_SR_inference_DFDNET and a question about DFDNET

### ISSUE THREAD

**Issue by BeauGeogeo** [NeonLeexiang/DLGSANet#6]
Good morning,

First of all thank you for sharing this great work ! I'd like to use it for a talking head project of the company I'm currently working for.

I tried to run the notebook for Basic SR inference but got the following error : 

> /usr/local/lib/python3.10/dist-packages/torchvision/transforms/functional_tensor.py:5: UserWarning: The torchvision.transforms.functional_tensor module is deprecated in 0.15 and will be **removed in 0.17**. Please don't rely on it. You probably just need to use APIs in torchvision.transforms.functional or in torchvision.transforms.v2.functional.
  warnings.warn(
Please install facexlib: pip install facexlib
Traceback (most recent call last):
  File "/content/BasicSR/inference/inference_dfdnet.py", line 114, in <module>
    net = DFDNet(64, dict_path=args.dict_path).to(device)
  File "/content/BasicSR/basicsr/archs/dfdnet_arch.py", line 77, in __init__
    self.dict = torch.load(dict_path)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 815, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 1033, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.

I also wanted to ask a question. You have scripts for DFDNET inference, why ? And where is exactly the script to test your own model DGLSANet ?

Thank you very much.

Best regards,

Geoffrey.

**Comment by NeonLeexiang** [comment]
Sorry for being late with the replies, the released code is simply based on the BasicSR framework, and the proposes of the released code is to offer the arch file of the main network structure of the DLGSANet.

We are sorry that we only offer the arch file and options file of the network structure with the pre-train models and some visual results.

**Comment by NeonLeexiang** [comment]
> Sorry for being late with the replies, the released code is simply based on the BasicSR framework, and the proposes of the released code is to offer the arch file of the main network structure of the DLGSANet.
> 
> We are sorry that we only offer the arch file and options file of the network structure with the pre-train models and some visual results.

Given that the official BasicSR framework provides the inference of several networks, I'll put it on my to-do list and get it done shortly.
